[repository.cargo-berger]
path="./"
default_branch="master"

    [repository.cargo-berger.rust]
    fmt = true
    clippy_hack = true
    sqlx = false

    [repository.cargo-berger.rust.ci]
    fmt = true
    clippy = true
