[repository.cargo-berger]
path="./"
default_branch="master"
remote_url="https://github.com/RustyNova016/cargo-berger"

    [repository.cargo-berger.release]
    git_cliff = true

[crate.cargo-berger]
path="./"

    [crate.cargo-berger.commit]
    fmt = true
    clippy_hack = true
    sqlx = false

    [crate.cargo-berger.ci]
    fmt = true
    doc = true
    clippy = true
    test = true
    nextest = true
    msrv = true
    machete = true
    semver = false
    # min_versions = true